Description:
    Alex Despotakis
    Cloud DevOps Engineering Part 2 Project

    This template seeks to replicate the schematics described in aws_diagram.png
    All of the resources are listed in alphabetical order by type and by name

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to a resource
        Type: String

    VpcCIDR:
        Description: Enter the IP range in CIDR notation for the VPC
        Type: String
        Default: 10.0.0.0/16

    PublicSubnet1CIDR:
        Description: IP range in CIDR notation for public subnet in VPC
        Type: String
        Default: 10.0.0.0/24

    PublicSubnet2CIDR:
        Description: IP range in CIDR notation for public subnet in VPC
        Type: String
        Default: 10.0.1.0/24

    PrivateSubnet1CIDR:
        Description: IP range in CIDR notation for private subnet in VPC
        Type: String
        Default: 10.0.2.0/24

    PrivateSubnet2CIDR:
        Description: IP range in CIDR notation for private subnet in VPC
        Type: String
        Default: 10.0.3.0/24


Resources:

    S3ReadOnlyEC2Role:
        Type: AWS::IAM::Role
        Properties:
            RoleName: S3ReadOnlyAccessEC2
            AssumeRolePolicyDocument:
                Statement:
                -   Action:
                    - sts:AssumeRole
                    Effect: Allow
                    Principal:
                        Service:
                        - ec2.amazonaws.com

    #instace profile contains the IAM Role name(s) that we want to associate to our auto scaling EC2 Servers
    ProfileWithRolesForOurApp:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Roles:
            - !Ref S3ReadOnlyEC2Role


Outputs:

    S3ReadAccessForEC2:
        Description: The IAM role that grants read only access to S3 buckets for EC2 servers
        Value: !Ref ProfileWithRolesForOurApp
        Export:
            Name: !Sub ${EnvironmentName}-S3ReadAccessForEC2