Description:
    Alex Despotakis
    Cloud DevOps Engineering Part 2 Project

    This template seeks to replicate the schematics described in aws_diagram.png
    All S3 related items will be found here.


Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to a resource
        Type: String

    VpcCIDR:
        Description: Enter the IP range in CIDR notation for the VPC
        Type: String
        Default: 10.0.0.0/16

    PublicSubnet1CIDR:
        Description: IP range in CIDR notation for public subnet in VPC
        Type: String
        Default: 10.0.0.0/24

    PublicSubnet2CIDR:
        Description: IP range in CIDR notation for public subnet in VPC
        Type: String
        Default: 10.0.1.0/24

    PrivateSubnet1CIDR:
        Description: IP range in CIDR notation for private subnet in VPC
        Type: String
        Default: 10.0.2.0/24

    PrivateSubnet2CIDR:
        Description: IP range in CIDR notation for private subnet in VPC
        Type: String
        Default: 10.0.3.0/24

    WebServerSSHKey:
        Description: The name of the SSH key pair for the EC2 web servers
        Type: String

    BastionServerSSHKey:
        Description: The name of the SSH key pair for the Bastion server
        Type: String

    SourceIp:
        Description: For the Bastion server, what IP we are cleared to SSH from.
        Type: String


Resources:


    S3Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: udagram-despotakis

    S3BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref S3Bucket
            PolicyDocument:
              Statement:
                  - Action:
                    - s3:GetObject
                    Effect: Allow
                    Resource: !Join ["", ["arn:aws:s3:::", !Ref S3Bucket, "/*"]]
                    Principal:
                        Service:
                        - ec2.amazonaws.com


Outputs:

    S3BucketArn:
        Description: References Udagram's S3 bucket
        Value: !Join ["", ["arn:aws:s3:::", !Ref S3Bucket]]
        Export:
            Name: !Sub ${EnvironmentName}-S3Arn
